version: '3'
services:
  api:
    container_name: api-auth
    build: ./
    ports:
      - '8181:8181'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=8181
      - PUT_TOKEN_URL=http://the-other-api/token
